# tasks/main.yml

- name: Actualizar el sistema
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Instalar Apache
  apt:
    name: apache2
    state: present

- name: Asegurarse de que el servicio de Apache esté iniciado y habilitado
  service:
    name: apache2
    state: started
    enabled: yes

- name: Reiniciar Apache
  service:
    name: apache2
    state: restarted
  when: ansible_service_mgr == "systemd"

