---
- name: Tareas para grupo1
  hosts: Ubuntu
  become: yes
  tasks:
    - name: Instalar un paquete en grupo1
      apt:
        name: curl
        state: present

- name: Tareas para grupo2
  hosts: Debian
  become: yes
  tasks:
    - name: Instalar un paquete en grupo2
      apt:
        name: apache2
        state: present
