---
- name: Actualizar servidores de manera orquestada
  hosts: all
  become: yes
  serial: 1  # Actualiza un servidor a la vez
  max_fail_percentage: 10  # Permite un máximo del 10% de fallos

  tasks:
    - name: Actualizar el sistema
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Actualizar el sistema
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Reiniciar servicios críticos
      service:
        name: "{{ item }}"
        state: restarted
      loop:
        - nginx
        - apache2 
      when: ansible_os_family == "Debian"

    - name: Reiniciar servicios críticos
      service:
        name: "{{ item }}"
        state: restarted
      loop:
        - httpd 
      when: ansible_os_family == "RedHat"

    - name: Comprobar el estado del servidor
      wait_for:
        port: 80
        delay: 5
        timeout: 300
      register: result
      until: result is success

